### ISSUE TITLE
passing options

### ISSUE THREAD

**Issue by StephenMayeux** [normanjoyner/node-quandl#8]
Is it possible to pass additional options when I instantiate the Quandl object? I'd really like the data to be displayed in ascending order, and I only want the date and closing stock prices. I can achieve this by making a simple GET request in jQuery:

 **https://www.quandl.com/api/v3/datasets/WIKI/FB.json?order=asc&exclude_column_names=true&start_date=2015-01-30&end_date=2016-01-29&column_index=4**

But I can't find anywhere in the docs that show me how to limit and configure my results using the node module. I tried this:

```
var quandl = new Quandl({
  auth_token: 'MY API TOKEN',
  api_version: 3,
  order: 'asc',
  exclude_column_names: true,
  start_date: '2015-01-30',
  end_date: '2016-01-29',
  column_index: 4
});
```

But the additional options do not change the output.

 Please let me know if it's possible, and thank you!

**Comment by normanjoyner** [comment]
Yes it is possible! Rather than configuring the `quandl` client with those parameters, you can modify individual requests as seen below:

```javascript
var quandl = new Quandl({
  auth_token: "MY API TOKEN",
  api_version: 3
});

quandl.dataset({
  source: "WIKI",
  table: "FB"
}, {
  order: "asc",
  exclude_column_names: true,
  start_date: "2015-01-30",
  end_date: "2016-01-29",
  column_index: 4
}, function(err, response){
    if(err)
        throw err;

    console.log(response);
});
```
The second object passed to the method will be treated as query string parameters.

I hope this helps! Feel free to close if this is sufficient; otherwise, I can help with further issues.

**Comment by StephenMayeux** [comment]
Works like a charm. Thanks!
